[package]
name = "fcm-n"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.37", features = ["fs"] }
thiserror = "1.0"
serde_json = "1.0"
jsonwebtoken = "9.3"
